framework:
    cache:
        directory: '%kernel.cache_dir%/pools'
        default_doctrine_provider: 'app.doctrine_cache'
        default_psr6_provider: 'app.my_psr6_service'
        default_redis_provider: 'redis://localhost'
        default_memcached_provider: 'memcached://localhost'
        default_pdo_provider: 'doctrine.dbal.default_connection'
        app: cache.adapter.filesystem
        system: cache.adapter.system
        pools:
            custom_thing.cache:
                adapter: cache.app
