# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            'App\Message\SmsNotification': async
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
