# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            sync: 'sync://'
            yours: 'my-transport://...'
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # queue_name is specific to the doctrine transport
                    queue_name: high

                    # for AMQP send to a separate exchange then queue
                    #exchange:
                    #    name: high
                    #queues:
                    #    messages_high: ~
                    # or redis try "group"
            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: low

        routing:
            'App\Message\SmsNotification': async
            'App\Message\AbstractAsyncMessage': async
            'App\Message\AsyncMessageInterface': async
            'My\Message\ToBeSentToTwoSenders': [async, audit]
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
            App\Message\SmsNotification: sync
            'App\Message\SmsNotification':  async_priority_low
            'App\Message\NewUserWelcomeEmail':  async_priority_high
