# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"
            sync: 'sync://'

        routing:
            'App\Message\SmsNotification': async
            'App\Message\AbstractAsyncMessage': async
            'App\Message\AsyncMessageInterface': async
            'My\Message\ToBeSentToTwoSenders': [async, audit]
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
            App\Message\SmsNotification: sync
