twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'email/default/templates': 'email'
        'backend/templates': 'admin'
        '%kernel.project_dir%/assets/images': images
        '%kernel.project_dir%/assets/styles': styles
    form_themes: ['bootstrap_4_layout.html.twig']
