#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

article_search:
  path:        /articles/{_locale}/search.{_format}
  controller:  App\Controller\ArticleController::search
  locale:      en
  format:      html
  requirements:
      _locale: en|fr
      _format: html|xml

blog_index:
    path:       /blog/{page}
    controller: App\Controller\BlogController::index
    defaults:
        page: 1
        title: "Hello world!"

blog_list:
    path: /blog/{page<\d+>?1}
    controller: App\Controller\BlogController::list

blog_show:
    path:       /blog/{slug}
    controller: App\Controller\BlogController::show

api_post_show:
    path:       /api/posts/{id}
    controller: App\Controller\BlogApiController::show
    methods:    GET|HEAD

api_post_edit:
    path:       /api/posts/{id}
    controller: App\Controller\BlogApiController::edit
    methods:    PUT

contact:
    path:       /contact
    controller: 'App\Controller\DefaultController::contact'
    condition:  "context.getMethod() in ['GET', 'HEAD'] and request.headers.get('User-Agent') matches '/firefox/i'"
